version: '3.9'
services:
  birthday-bot:
    build: .
    container_name: birthday-bot-container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data 
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      SERVER_ID: ${SERVER_ID}
      CHANNEL_ID: ${CHANNEL_ID}